theme: jekyll-theme-tactile
title: Daniel William Rivers
logo: /docs/assets/images/robot.png
description: <a href="mailto:dannywrivers@gmail.com">dannywrivers@gmail.com</a> * (520) 275-9638 * [linkedin](https://www.linkedin.com/in/danny-rivers-639824149/) 
