title: Daniel William Rivers
theme: jekyll-theme-tactile
logo: /docs/assets/images/robot.png
description: <a href="mailto:dannywrivers@gmail.com">dannywrivers@gmail.com</a> * (520) 275-9638 * <a href="https://www.linkedin.com/in/danny-rivers-639824149/" target="_blank">linkedin</a>
